/* Generated by Yosys 0.30+48 (git sha1 14d50a176, gcc 11.3.0-1ubuntu1~22.04.1 -fPIC -Os) */

module or2(a, b, c);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'he >> { a, b };
endmodule
